/*Create database HipsterRentalCorp;*/

Create Table KUNDE
(
KUNDENNR varchar(10) NOT NULL,
VORNAME varchar(255),
NACHNAME varchar(255),
EMAIL varchar(255) REFERENCES USER(EMAIL),
ORGANISATIONSNAME varchar(255),
STRASSE varchar(255),
HAUSNUMMER varchar(10),
PLZ varchar(10) REFERENCES ORTE(PLZ),
TELEFONNR varchar(255),
HANDYNR varchar(255),
PRIMARY KEY (KUNDENNR)
);

CREATE TABLE WARENKORB
(
KUNDENNR varchar(10) NOT NULL REFERENCES KUNDE(KUNDENNR),
WARENKORBPRODUKTNR varchar(10) REFERENCES WARENKORBPRODUKT(WARENKORBPRODUKTNR),
WARENKORBPAKETNR varchar(10) REFERENCES WARENKORBPAKET(WARENKORBPAKETNR),
PRIMARY KEY(KUNDENNR)
);

CREATE TABLE WARENKORBPRODUKT
(
WARENKORBPRODUKTNR varchar(10) NOT NULL,
PRODUKTNR varchar(10) REFERENCES PRODUKT(PRODUKTNR),
PRIMARY KEY(WARENKORBPRODUKTNR)
);

CREATE TABLE WARENKORBPAKET
(
WARENKORBPAKETNR varchar(10) NOT NULL,
PAKETNR varchar(10) REFERENCES PAKET(PAKETNR),
PRIMARY KEY(WARENKORBPAKETNR)
);

CREATE TABLE ORTE
(
PLZ varchar(10) NOT NULL,
Ort varchar(255),
PRIMARY KEY (PLZ)
);

Create Table MITARBEITER
(
MITARBEITERNR varchar(10) NOT NULL,
VORNAME varchar(255),
NACHNAME varchar(255),
EMAIL varchar(255) REFERENCES USER(EMAIL),
PRIMARY KEY (MITARBEITERNR)
);

Create Table USER
(
EMAIL varchar(255) NOT NULL,
PASSWORT varchar(255) NOT NULL,
ISADMIN varchar(1),
PRIMARY KEY (EMAIL)
);

CREATE TABLE BESTELLUNG
(
BESTELLNR varchar(10) NOT NULL,
VON timestamp,
BIS timestamp,
KUNDENNR varchar(10) REFERENCES KUNDE(KUNDENNR),
BESTAETIGT varchar(1),
PRIMARY KEY (BESTELLNR)
);

CREATE TABLE BESTELLPRODUKTPOS
(
BESTELLNR varchar(10) NOT NULL REFERENCES BESTELLUNG(BESTELLNR),
PRODUKTNR varchar(10) NOT NULL REFERENCES PRODUKT(PRODUKTNR),
PRIMARY KEY (BESTELLNR, PRODUKTNR)
);

CREATE TABLE BESTELLPAKETPOS
(
BESTELLNR varchar(10) NOT NULL REFERENCES BESTELLUNG(BESTELLNR),
PAKETNR varchar(10) NOT NULL REFERENCES PAKET(PAKETNR),
PRIMARY KEY (BESTELLNR, PAKETNR)
);

CREATE TABLE FOTO
(
FOTONR varchar(10) NOT NULL,
FOTO varchar(255),
PRIMARY KEY (FOTONR)
);

CREATE TABLE FOTOPOS
(
FOTONR varchar(10) NOT NULL REFERENCES FOTO(FOTONR),
PRODUKTNR varchar(10) NOT NULL REFERENCES PRODUKT(PRODUKTNR),
PRIMARY KEY (FOTONR, PRODUKTNR)
);

CREATE TABLE PRODUKT
(
PRODUKTNR varchar(10) NOT NULL,
BEZEICHNUNG varchar(255),
HERSTELLERNAME varchar(255),
BESCHREIBUNG varchar(255),
DETAILS varchar(255),
MIETZINS varchar(10),
KATEGORIENR varchar(10) REFERENCES KATEGORIE(KATEGORIENR),
ALTERNATIVE varchar(10) REFERENCES PRODUKT(PRODUKTNR),
PRIMARY KEY (PRODUKTNR)
);

CREATE TABLE KATEGORIE
(
KATEGORIENR varchar(10) NOT NULL,
NAME varchar(255),
FOTONR varchar(10) REFERENCES FOTOS(FOTONR),
UNTERKATEGORIE varchar(10) REFERENCES KATEGORIE(KATEGORIENR),
PRIMARY KEY (KATEGORIENR)
);

CREATE TABLE PAKET
(
PAKETNR varchar(10) NOT NULL,
KATEGORIENR varchar(10) REFERENCES KATEGORIE(KATEGORIENR),
BEZEICHNUNG varchar(255) NOT NULL,
BESCHREIBUNG varchar(255),
DETAILS varchar(255),
MIETZINS varchar(10) NOT NULL,
FOTONR varchar(10) REFERENCES FOTO(FOTONR),
PRIMARY KEY (PAKETNR)
);

CREATE TABLE PAKETPOS
(
PAKETNR varchar(10) NOT NULL REFERENCES PAKET(PAKETNR),
PRODUKTNR varchar(10) NOT NULL REFERENCES PRODUKT(PRODUKTNR),
PRIMARY KEY (PAKETNR, PRODUKTNR)
);


/* Daten */
/* ORTE */
INSERT INTO ORTE VALUES('24106', 'Kiel');

/* KUNDE */
Insert into KUNDE Values('KNR000001', 'Peter', 'Panda', 'sunnyboy@knute.de', 'JohnnyCottenIndustries', 'Holzweg', '13a', '24106', '0431 666514', '0171 80666737');

/* MITARBEITER */
INSERT INTO MITARBEITER VALUES( 'MNR0000001', 'Manfred','Itarbeiter','Mani@HRC.de');

/* USER */
INSERT INTO USER VALUES('Mani@HRC.de','12345','j');
INSERT INTO USER VALUES('sunnyboy@knute.de','12345','');

/* FOTO */
INSERT INTO FOTO VALUES('FNR0000001','C:\\bla.jpg');
INSERT INTO FOTO VALUES('FNR0000002','C:\\bla1.png');

/* KATEGORIE */
INSERT INTO KATEGORIE VALUES('KATNR00001','Subwoofer','FNR0000001', '');
INSERT INTO KATEGORIE VALUES('KATNR00002','Funk','FNR0000002', 'KATNR00003');
INSERT INTO KATEGORIE VALUES('KATNR00003','Funkgeräte','FNR0000002', '');

/* PRODUKT */
INSERT INTO PRODUKT VALUES('PNR0000001','SubwuufeR','Intel','Ey, das geht ab...','400V Starkstrom mit eingegebautem Backofen','12,45','KATNR00001', 'PNR0000002');
INSERT INTO PRODUKT VALUES('PNR0000002','Radio','Macintosh','Hammerfettbombekrass','9,5 V Batterie ben�tigt', '3,25','KATNR00002', '');
INSERT INTO PRODUKT VALUES('PNR0000003','Trucker Funkgerät','Hama','Dem Trucker sein Schätzeke.','Kurz-, Mittel- und Langwelle', '14,89','KATNR00003', '');
INSERT INTO PRODUKT VALUES('PNR0000004','Amateur Funkgerät','Hama','Für den frischen Funker','Kurz- und Mittelwelle', '9,99','KATNR00003', 'PNR0000003');

/* FOTOPOS */
INSERT INTO FOTOPOS VALUES('FNR0000001', 'PNR0000001');
INSERT INTO FOTOPOS VALUES('FNR0000002', 'PNR0000001');

/* BESTELLUNG */
INSERT INTO BESTELLUNG VALUES('BNR0000001', '2015-10-12 16:30:00','2015-10-16 12:45:00','KNR0000001','');

/* BESTELLPRODUKTPOS */
INSERT INTO BESTELLPRODUKTPOS VALUES('BNR0000001','PNR0000001');
INSERT INTO BESTELLPRODUKTPOS VALUES('BNR0000001','PNR0000002');

/* BESTELLPAKETPOS */
INSERT INTO BESTELLPAKETPOS VALUES('BNR0000001','PAKNR00001');

/* PAKET */
INSERT INTO PAKET VALUES('PAKNR00001', 'KATNR00001', 'Rdiwf-Paket', 'Radio und Subwoofer', '400 V Starkstrom, 9,5 V Batterie', '60,99', 'FNR0000001');

/* PAKETPOS */
INSERT INTO PAKETPOS VALUES('PAKNR00001', 'PNR0000001');
INSERT INTO PAKETPOS VALUES('PAKNR00001', 'PNR0000002');
